version: "3.8"

# used for security to ensure we only have the connectios specified
networks:
  inception-net:
    driver: bridge
    name: inception-net

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      device: /home/znichola/data/wordpress
      type: none
      o: bind
  db:
    driver: local
    name: db
    driver_opts:
      device: /home/znichola/data/mariadb
      type: none
      o: bind

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    networks:
      - inception-net
    ports:
      - "443:443"
    volumes:
      - wp:/website

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    networks:
      - inception-net
    ports:
      - "9000:9000"
    volumes:
      - wp:/website
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - WP_USER=${WP_USER}
        - WP_USER_PWD=${WP_USER_PWD}
    networks:
      - inception-net
    ports:
      - "3306:3306"
    volumes:
      - db:/database
