version: "3.8"

# used for security to ensure we only have the connectios specified
networks:
  inception-net:
    driver: bridge
    name: inception-net

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      device: /home/znichola/data/wordpress
      type: none
      o: bind
  db:
    driver: local
    name: db
    driver_opts:
      device: /home/znichola/data/mariadb
      type: none
      o: bind
  sv:
    driver: local
    name: sv
    driver_opts:
      device: /home/znichola/data/svelt
      type: none
      o: bind

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    networks:
      - inception-net
    ports:
      - "443:443"
    volumes:
      - wp:/website
    depends_on:
      - wordpress
    # restart: on-failure

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    networks:
      - inception-net
    volumes:
      - wp:/website
    env_file:
      - .env
    depends_on:
      - mariadb
    # restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    networks:
      - inception-net
    volumes:
      - db:/database
    # restart: on-failure
    env_file:
      - .env

  ftp_server:
    container_name: ftp_server
    build: requirements/bonus/ftp_server
    networks:
      - inception-net
    volumes:
      - wp:/home/$WP_ADMIN
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    env_file:
      - .env
    depends_on:
      - wordpress
    init: true
    restart: always

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    networks:
      - inception-net
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    init: true
    restart: always

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    networks:
      - inception-net
    ports:
      - "6379:6379"
    depends_on:
      - wordpress
    restart: always

  svelt:
    container_name: svelt
    build: ./requirements/bonus/svelt/
    networks:
      - inception-net
    volumes:
      - sv:/root/sveltapp
    ports:
      - "5173:5173"
    restart: always
    init: true
