version: "3.8"

# used for security to ensure we only have the connectios specified
networks:
  docker-network:
    # name: docker-network
    driver: bridge


services:
  nginx:
    container_name: nginx
    networks:
      - docker-network
    build: requirements/nginx
    ports:
      - "443:443"

